# Generated by Django 4.1.5 on 2024-12-24 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(blank=True, max_length=500)),
                ('article_commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
    ]
